"""

Revision ID: 07d789ee1be9
Revises: 530fd04fe149
Create Date: 2024-03-22 11:38:42.983985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d789ee1be9'
down_revision = '530fd04fe149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_in_proj',
    sa.Column('emploeer_id', sa.Integer(), nullable=True),
    sa.Column('carts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carts_id'], ['carts_info.id'], ),
    sa.ForeignKeyConstraint(['emploeer_id'], ['workers.id'], )
    )
    op.create_table('participants_in_proj',
    sa.Column('emploeer_id', sa.Integer(), nullable=True),
    sa.Column('carts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carts_id'], ['carts_info.id'], ),
    sa.ForeignKeyConstraint(['emploeer_id'], ['workers.id'], )
    )
    op.create_table('responsible_in_proj',
    sa.Column('emploeer_id', sa.Integer(), nullable=True),
    sa.Column('carts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carts_id'], ['carts_info.id'], ),
    sa.ForeignKeyConstraint(['emploeer_id'], ['workers.id'], )
    )
    op.drop_table('employe_in_proj')
    op.add_column('emploe_group', sa.Column('id', sa.Integer(), nullable=True))
    op.drop_constraint('emploe_group_emploeer_id_fkey', 'emploe_group', type_='foreignkey')
    op.create_foreign_key(None, 'emploe_group', 'workers', ['emploeer_id'], ['id'])
    op.create_foreign_key(None, 'emploe_group', 'group_workers', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emploe_group', type_='foreignkey')
    op.drop_constraint(None, 'emploe_group', type_='foreignkey')
    op.create_foreign_key('emploe_group_emploeer_id_fkey', 'emploe_group', 'group_workers', ['emploeer_id'], ['id'])
    op.drop_column('emploe_group', 'id')
    op.create_table('employe_in_proj',
    sa.Column('emploeer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('carts_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['carts_id'], ['carts_info.id'], name='employe_in_proj_carts_id_fkey'),
    sa.ForeignKeyConstraint(['emploeer_id'], ['workers.id'], name='employe_in_proj_emploeer_id_fkey')
    )
    op.drop_table('responsible_in_proj')
    op.drop_table('participants_in_proj')
    op.drop_table('manager_in_proj')
    # ### end Alembic commands ###
