"""

Revision ID: 0c26e43cf32d
Revises: 6c4130665c74
Create Date: 2024-03-25 13:01:11.904816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c26e43cf32d'
down_revision = '6c4130665c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
