"""

Revision ID: 11b393c56924
Revises: d6c1f650165a
Create Date: 2024-03-22 08:45:18.866470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b393c56924'
down_revision = 'd6c1f650165a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
