"""

Revision ID: 530fd04fe149
Revises: 11b393c56924
Create Date: 2024-03-22 09:01:35.439033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530fd04fe149'
down_revision = '11b393c56924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
