"""

Revision ID: 603be93b4931
Revises: 07d789ee1be9
Create Date: 2024-03-22 12:33:22.252533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603be93b4931'
down_revision = '07d789ee1be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emploe_group', sa.Column('group_workers_id', sa.Integer(), nullable=True))
    op.drop_constraint('emploe_group_id_fkey', 'emploe_group', type_='foreignkey')
    op.create_foreign_key(None, 'emploe_group', 'group_workers', ['group_workers_id'], ['id'])
    op.drop_column('emploe_group', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emploe_group', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'emploe_group', type_='foreignkey')
    op.create_foreign_key('emploe_group_id_fkey', 'emploe_group', 'group_workers', ['id'], ['id'])
    op.drop_column('emploe_group', 'group_workers_id')
    # ### end Alembic commands ###
