"""

Revision ID: 6a07a67cfa4b
Revises: 
Create Date: 2024-03-14 08:01:44.987647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a07a67cfa4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('personal_phone', sa.String(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('work_phone', sa.String(), nullable=True),
    sa.Column('internal_phone', sa.String(), nullable=True),
    sa.Column('telegramm', sa.String(), nullable=True),
    sa.Column('skype', sa.String(), nullable=True),
    sa.Column('bitrix24', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('personal_photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers')
    # ### end Alembic commands ###
