"""

Revision ID: 6c4130665c74
Revises: 9a7c36a96f84
Create Date: 2024-03-25 08:56:57.122675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4130665c74'
down_revision = '9a7c36a96f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
