"""

Revision ID: 9a7c36a96f84
Revises: 603be93b4931
Create Date: 2024-03-25 07:15:33.338798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7c36a96f84'
down_revision = '603be93b4931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emploe_group', sa.Column('id', sa.Integer(), nullable=True))
    op.drop_constraint('emploe_group_group_workers_id_fkey', 'emploe_group', type_='foreignkey')
    op.create_foreign_key(None, 'emploe_group', 'group_workers', ['id'], ['id'])
    op.drop_column('emploe_group', 'group_workers_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emploe_group', sa.Column('group_workers_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'emploe_group', type_='foreignkey')
    op.create_foreign_key('emploe_group_group_workers_id_fkey', 'emploe_group', 'group_workers', ['group_workers_id'], ['id'])
    op.drop_column('emploe_group', 'id')
    # ### end Alembic commands ###
