"""

Revision ID: a6d62f4cf68c
Revises: 
Create Date: 2024-03-21 14:39:51.188225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d62f4cf68c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('delivered', sa.DateTime(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('personal_phone', sa.String(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('group_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('personal_phone', sa.String(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('work_phone', sa.String(), nullable=True),
    sa.Column('internal_phone', sa.String(), nullable=True),
    sa.Column('telegramm', sa.String(), nullable=True),
    sa.Column('skype', sa.String(), nullable=True),
    sa.Column('bitrix24', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('personal_photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('clients_group_in_proj',
    sa.Column('clients_id', sa.Integer(), nullable=True),
    sa.Column('carts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carts_id'], ['carts_info.id'], ),
    sa.ForeignKeyConstraint(['clients_id'], ['clients.id'], )
    )
    op.create_table('emploe_group',
    sa.Column('emploeer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emploeer_id'], ['group_workers.id'], )
    )
    op.create_table('employe_in_proj',
    sa.Column('emploeer_id', sa.Integer(), nullable=True),
    sa.Column('carts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carts_id'], ['carts_info.id'], ),
    sa.ForeignKeyConstraint(['emploeer_id'], ['workers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe_in_proj')
    op.drop_table('emploe_group')
    op.drop_table('clients_group_in_proj')
    op.drop_table('workers')
    op.drop_table('group_workers')
    op.drop_table('clients')
    op.drop_table('carts_info')
    # ### end Alembic commands ###
