"""

Revision ID: c5da0609c11c
Revises: 0c26e43cf32d
Create Date: 2024-03-26 06:44:30.058120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5da0609c11c'
down_revision = '0c26e43cf32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
