"""

Revision ID: d6c1f650165a
Revises: d9ea72b48dd1
Create Date: 2024-03-22 08:34:41.691514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c1f650165a'
down_revision = 'd9ea72b48dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
